function(enable_doxygen)
    option(ENABLE_DOXYGEN "Enable doxygen doc builds of source" OFF)
    if(ENABLE_DOXYGEN)
        # The contents of the default Doxyfile file generated by doxygen_add_docs() can be customized by setting CMake variables
        # before calling doxygen_add_docs(). Any variable with a name of the form DOXYGEN_<tag> will have its value substituted
        # for the corresponding <tag> configuration option in the Doxyfile
        set(DOXYGEN_CALLER_GRAPH ON)
        set(DOXYGEN_CALL_GRAPH ON)
        set(DOXYGEN_EXTRACT_ALL ON)
        # find doxygen package
        find_package(Doxygen)
        #find_package(Doxygen REQUIRED dot) # TODO enable dot when graphviz is installed properly.
        if(DOXYGEN_FOUND)
            doxygen_add_docs(doxygen-docs ${PROJECT_SOURCE_DIR})
        else()
            message(SEND_ERROR "doxygen not found, cannot generate doxygen docs")
        endif()
    endif()
endfunction()