def configure(ctx):
    print(f"--> running configure from {ctx.path.abspath()}")

def ping(ctx):
    print (f"--> ping from {ctx.path.abspath()}")
    ctx.recurse('src')  # ctx.recurse() will call the same python function in src/wscript
