function(enable_doxygen)
    option(ENABLE_DOC "Enable doxygen documentation builds of source" ON)
#    if(CMAKE_BUILD_TYPE MATCHES ^[Rr]elease AND ENABLE_DOC)
        if(ENABLE_DOC)
        # The contents of the default Doxyfile file generated by doxygen_add_docs() can be customized by setting CMake variables
        # before calling doxygen_add_docs(). Any variable with a name of the form DOXYGEN_<tag> will have its value substituted
        # for the corresponding <tag> configuration option in the Doxyfile.
        # We disable this for now as we dont use official FindDoxygen.cmake that ships with cmake. We instead use a Findoxygen
        # generated by conan cmake_find_package generator. Any configuration is done inside a Doxyfile.in template file
        # using configure_file()

        #set(DOXYGEN_CALLER_GRAPH ON)
        #set(DOXYGEN_CALL_GRAPH ON)
        #set(DOXYGEN_EXTRACT_ALL ON)
        # find doxygen package
        # find_package(Doxygen)
        #find_package(Doxygen REQUIRED dot) # TODO enable dot when graphviz is installed properly.
        #        if(DOXYGEN_FOUND)
        #            doxygen_add_docs(doxygen-docs ${PROJECT_SOURCE_DIR})
        #        else()
        #            message(SEND_ERROR "doxygen not found, cannot generate doxygen docs")
        #        endif()

        find_package(doxygen)
        if(doxygen_FOUND)
            find_program(DOXYGEN_EXECUTABLE doxygen REQUIRED)
            # configure doxygen
            set(DOXYGEN_IN_FILE ${CMAKE_SOURCE_DIR}/docs/Doxyfile.in)
            set(DOXYGEN_OUT_FILE ${CMAKE_BINARY_DIR}/Doxyfile)
            configure_file(${DOXYGEN_IN_FILE} ${DOXYGEN_OUT_FILE})

            # generate configuration, note that conan puts doxygen binary in $PATH, so we can call it directly
            add_custom_target(doxygen_documentation ALL
                    COMMAND ${DOXYGEN_EXECUTABLE} ${DOXYGEN_OUT_FILE}
                    WORKING_DIRECTORY ${CMAKE_BINARY_DIR}
                    COMMENT "generating doxygen documentation"
                    VERBATIM)
        else()
            message(SEND_ERROR "building documentation (-DENABLE_DOC=ON) is enabled, but doxygen not found")
        endif()
    endif()
endfunction()
